OBJS = LUtil.cpp main.cpp LTexture.cpp

CC = g++

COMPILER_FLAGS = -w

LINKER_FLAGS = -lGL -lGLU -lglut -lIL -lILU

OBJ_NAME = output

all: $(OBJS)
	$(CC) $(OBJS) $(COMPILER_FLAGS) $(LINKER_FLAGS) -o $(OBJ_NAME)
